// Created by iWeb 3.0.3 local-build-20110623

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-4,3,6,227),url:'pepito_files/stroke.png'},{rect:new IWRect(-4,-3,6,6),url:'pepito_files/stroke_1.png'},{rect:new IWRect(2,-3,624,6),url:'pepito_files/stroke_2.png'},{rect:new IWRect(626,-3,6,6),url:'pepito_files/stroke_3.png'},{rect:new IWRect(626,3,6,227),url:'pepito_files/stroke_4.png'},{rect:new IWRect(626,230,6,6),url:'pepito_files/stroke_5.png'},{rect:new IWRect(2,230,624,7),url:'pepito_files/stroke_6.png'},{rect:new IWRect(-3,230,5,6),url:'pepito_files/stroke_7.png'}],new IWSize(630,234)),stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,261),url:'pepito_files/stroke_16.png'},{rect:new IWRect(-3,-4,6,7),url:'pepito_files/stroke_17.png'},{rect:new IWRect(3,-4,600,7),url:'pepito_files/stroke_18.png'},{rect:new IWRect(603,-4,6,7),url:'pepito_files/stroke_19.png'},{rect:new IWRect(603,3,7,261),url:'pepito_files/stroke_20.png'},{rect:new IWRect(603,264,4,5),url:'pepito_files/stroke_21.png'},{rect:new IWRect(3,264,600,6),url:'pepito_files/stroke_22.png'},{rect:new IWRect(-3,264,6,7),url:'pepito_files/stroke_23.png'}],new IWSize(606,268)),stroke_1:new IWStrokeParts([{rect:new IWRect(-4,3,5,142),url:'pepito_files/stroke_8.png'},{rect:new IWRect(-4,-2,5,5),url:'pepito_files/stroke_9.png'},{rect:new IWRect(1,-2,600,5),url:'pepito_files/stroke_10.png'},{rect:new IWRect(601,-1,6,4),url:'pepito_files/stroke_11.png'},{rect:new IWRect(601,3,7,142),url:'pepito_files/stroke_12.png'},{rect:new IWRect(601,145,7,6),url:'pepito_files/stroke_13.png'},{rect:new IWRect(1,145,600,7),url:'pepito_files/stroke_14.png'},{rect:new IWRect(-3,145,4,6),url:'pepito_files/stroke_15.png'}],new IWSize(605,149))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('pepito_files/pepitoMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
