// Created by iWeb 3.0.3 local-build-20110623

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,315),url:'dimelo_files/stroke_16.png'},{rect:new IWRect(-3,-4,6,7),url:'dimelo_files/stroke_17.png'},{rect:new IWRect(3,-3,638,6),url:'dimelo_files/stroke_18.png'},{rect:new IWRect(641,-4,4,7),url:'dimelo_files/stroke_19.png'},{rect:new IWRect(641,3,6,315),url:'dimelo_files/stroke_20.png'},{rect:new IWRect(641,318,6,6),url:'dimelo_files/stroke_21.png'},{rect:new IWRect(3,318,638,6),url:'dimelo_files/stroke_22.png'},{rect:new IWRect(-3,318,6,6),url:'dimelo_files/stroke_23.png'}],new IWSize(644,322)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,3,5,336),url:'dimelo_files/stroke.png'},{rect:new IWRect(-3,-2,6,5),url:'dimelo_files/stroke_1.png'},{rect:new IWRect(3,-2,642,5),url:'dimelo_files/stroke_2.png'},{rect:new IWRect(645,-2,4,5),url:'dimelo_files/stroke_3.png'},{rect:new IWRect(645,3,6,336),url:'dimelo_files/stroke_4.png'},{rect:new IWRect(645,339,6,4),url:'dimelo_files/stroke_5.png'},{rect:new IWRect(3,339,642,6),url:'dimelo_files/stroke_6.png'},{rect:new IWRect(-3,339,6,6),url:'dimelo_files/stroke_7.png'}],new IWSize(648,342)),stroke_1:new IWStrokeParts([{rect:new IWRect(-3,3,6,284),url:'dimelo_files/stroke_8.png'},{rect:new IWRect(-3,-4,6,7),url:'dimelo_files/stroke_9.png'},{rect:new IWRect(3,-3,630,6),url:'dimelo_files/stroke_10.png'},{rect:new IWRect(633,-4,4,7),url:'dimelo_files/stroke_11.png'},{rect:new IWRect(633,3,6,284),url:'dimelo_files/stroke_12.png'},{rect:new IWRect(633,287,6,6),url:'dimelo_files/stroke_13.png'},{rect:new IWRect(3,287,630,6),url:'dimelo_files/stroke_14.png'},{rect:new IWRect(-3,287,6,6),url:'dimelo_files/stroke_15.png'}],new IWSize(636,291))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('dimelo_files/dimeloMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
