// Created by iWeb 3.0.3 local-build-20110623

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,3,5,389),url:'para_tu_amor_files/stroke.png'},{rect:new IWRect(-3,-2,6,5),url:'para_tu_amor_files/stroke_1.png'},{rect:new IWRect(3,-2,641,5),url:'para_tu_amor_files/stroke_2.png'},{rect:new IWRect(644,-2,5,5),url:'para_tu_amor_files/stroke_3.png'},{rect:new IWRect(644,3,7,389),url:'para_tu_amor_files/stroke_4.png'},{rect:new IWRect(644,392,7,4),url:'para_tu_amor_files/stroke_5.png'},{rect:new IWRect(3,392,641,6),url:'para_tu_amor_files/stroke_6.png'},{rect:new IWRect(-3,392,6,6),url:'para_tu_amor_files/stroke_7.png'}],new IWSize(648,395)),stroke_1:new IWStrokeParts([{rect:new IWRect(-3,3,6,179),url:'para_tu_amor_files/stroke_8.png'},{rect:new IWRect(-3,-4,6,7),url:'para_tu_amor_files/stroke_9.png'},{rect:new IWRect(3,-3,639,6),url:'para_tu_amor_files/stroke_10.png'},{rect:new IWRect(642,-4,3,7),url:'para_tu_amor_files/stroke_11.png'},{rect:new IWRect(642,3,5,179),url:'para_tu_amor_files/stroke_12.png'},{rect:new IWRect(642,182,5,6),url:'para_tu_amor_files/stroke_13.png'},{rect:new IWRect(3,182,639,6),url:'para_tu_amor_files/stroke_14.png'},{rect:new IWRect(-3,182,6,6),url:'para_tu_amor_files/stroke_15.png'}],new IWSize(644,186))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('para_tu_amor_files/para_tu_amorMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixAllIEPNGs('Media/transparent.gif');IMpreload('para_tu_amor_files','shapeimage_2','0');IMpreload('para_tu_amor_files','shapeimage_2','1');IMpreload('para_tu_amor_files','shapeimage_2','2');IMpreload('para_tu_amor_files','shapeimage_2','3');applyEffects()}
function onPageUnload()
{Widget.onunload();}
