// Created by iWeb 3.0.3 local-build-20110623

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,3,5,440),url:'i_am_a_piano_files/stroke_8.png'},{rect:new IWRect(-3,-2,6,5),url:'i_am_a_piano_files/stroke_9.png'},{rect:new IWRect(3,-2,641,5),url:'i_am_a_piano_files/stroke_10.png'},{rect:new IWRect(644,-2,5,5),url:'i_am_a_piano_files/stroke_11.png'},{rect:new IWRect(644,3,7,440),url:'i_am_a_piano_files/stroke_12.png'},{rect:new IWRect(644,443,7,4),url:'i_am_a_piano_files/stroke_13.png'},{rect:new IWRect(3,443,641,6),url:'i_am_a_piano_files/stroke_14.png'},{rect:new IWRect(-3,443,6,6),url:'i_am_a_piano_files/stroke_15.png'}],new IWSize(648,446)),stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,551),url:'i_am_a_piano_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'i_am_a_piano_files/stroke_1.png'},{rect:new IWRect(3,-3,634,6),url:'i_am_a_piano_files/stroke_2.png'},{rect:new IWRect(637,-3,6,6),url:'i_am_a_piano_files/stroke_3.png'},{rect:new IWRect(637,3,7,551),url:'i_am_a_piano_files/stroke_4.png'},{rect:new IWRect(637,554,5,5),url:'i_am_a_piano_files/stroke_5.png'},{rect:new IWRect(3,554,634,5),url:'i_am_a_piano_files/stroke_6.png'},{rect:new IWRect(-3,554,6,4),url:'i_am_a_piano_files/stroke_7.png'}],new IWSize(641,556)),stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,212),url:'i_am_a_piano_files/stroke_16.png'},{rect:new IWRect(-3,-4,6,7),url:'i_am_a_piano_files/stroke_17.png'},{rect:new IWRect(3,-3,639,6),url:'i_am_a_piano_files/stroke_18.png'},{rect:new IWRect(642,-4,3,7),url:'i_am_a_piano_files/stroke_19.png'},{rect:new IWRect(642,3,5,212),url:'i_am_a_piano_files/stroke_20.png'},{rect:new IWRect(642,215,5,6),url:'i_am_a_piano_files/stroke_21.png'},{rect:new IWRect(3,215,639,6),url:'i_am_a_piano_files/stroke_22.png'},{rect:new IWRect(-3,215,6,6),url:'i_am_a_piano_files/stroke_23.png'}],new IWSize(644,219))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('i_am_a_piano_files/i_am_a_pianoMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
