// Created by iWeb 3.0.3 local-build-20110623

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,170),url:'nadie_como_tu_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'nadie_como_tu_files/stroke_1.png'},{rect:new IWRect(3,-3,610,6),url:'nadie_como_tu_files/stroke_2.png'},{rect:new IWRect(613,-3,6,6),url:'nadie_como_tu_files/stroke_3.png'},{rect:new IWRect(613,3,7,170),url:'nadie_como_tu_files/stroke_4.png'},{rect:new IWRect(613,173,5,6),url:'nadie_como_tu_files/stroke_5.png'},{rect:new IWRect(3,173,610,6),url:'nadie_como_tu_files/stroke_6.png'},{rect:new IWRect(-3,173,6,5),url:'nadie_como_tu_files/stroke_7.png'}],new IWSize(617,176)),stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,262),url:'nadie_como_tu_files/stroke_16.png'},{rect:new IWRect(-3,-4,6,7),url:'nadie_como_tu_files/stroke_17.png'},{rect:new IWRect(3,-3,619,6),url:'nadie_como_tu_files/stroke_18.png'},{rect:new IWRect(622,-4,3,7),url:'nadie_como_tu_files/stroke_19.png'},{rect:new IWRect(622,3,5,262),url:'nadie_como_tu_files/stroke_20.png'},{rect:new IWRect(622,265,5,6),url:'nadie_como_tu_files/stroke_21.png'},{rect:new IWRect(3,265,619,6),url:'nadie_como_tu_files/stroke_22.png'},{rect:new IWRect(-3,265,6,6),url:'nadie_como_tu_files/stroke_23.png'}],new IWSize(624,269)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,3,5,401),url:'nadie_como_tu_files/stroke_8.png'},{rect:new IWRect(-3,-2,6,5),url:'nadie_como_tu_files/stroke_9.png'},{rect:new IWRect(3,-2,617,5),url:'nadie_como_tu_files/stroke_10.png'},{rect:new IWRect(620,-2,5,5),url:'nadie_como_tu_files/stroke_11.png'},{rect:new IWRect(620,3,7,401),url:'nadie_como_tu_files/stroke_12.png'},{rect:new IWRect(620,404,7,4),url:'nadie_como_tu_files/stroke_13.png'},{rect:new IWRect(3,404,617,6),url:'nadie_como_tu_files/stroke_14.png'},{rect:new IWRect(-3,404,6,6),url:'nadie_como_tu_files/stroke_15.png'}],new IWSize(624,407))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('nadie_como_tu_files/nadie_como_tuMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixAllIEPNGs('Media/transparent.gif');IMpreload('nadie_como_tu_files','shapeimage_2','0');applyEffects()}
function onPageUnload()
{Widget.onunload();}
