// Created by iWeb 3.0.3 local-build-20110623

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,245),url:'tomalo_suave_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'tomalo_suave_files/stroke_1.png'},{rect:new IWRect(3,-3,625,6),url:'tomalo_suave_files/stroke_2.png'},{rect:new IWRect(628,-3,6,6),url:'tomalo_suave_files/stroke_3.png'},{rect:new IWRect(628,3,7,245),url:'tomalo_suave_files/stroke_4.png'},{rect:new IWRect(628,248,5,6),url:'tomalo_suave_files/stroke_5.png'},{rect:new IWRect(3,248,625,6),url:'tomalo_suave_files/stroke_6.png'},{rect:new IWRect(-3,248,6,5),url:'tomalo_suave_files/stroke_7.png'}],new IWSize(632,251)),stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,161),url:'tomalo_suave_files/stroke_16.png'},{rect:new IWRect(-3,-4,6,7),url:'tomalo_suave_files/stroke_17.png'},{rect:new IWRect(3,-3,605,6),url:'tomalo_suave_files/stroke_18.png'},{rect:new IWRect(608,-4,3,7),url:'tomalo_suave_files/stroke_19.png'},{rect:new IWRect(608,3,5,161),url:'tomalo_suave_files/stroke_20.png'},{rect:new IWRect(608,164,5,6),url:'tomalo_suave_files/stroke_21.png'},{rect:new IWRect(3,164,605,6),url:'tomalo_suave_files/stroke_22.png'},{rect:new IWRect(-3,164,6,6),url:'tomalo_suave_files/stroke_23.png'}],new IWSize(610,168)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,3,5,340),url:'tomalo_suave_files/stroke_8.png'},{rect:new IWRect(-3,-2,6,5),url:'tomalo_suave_files/stroke_9.png'},{rect:new IWRect(3,-2,618,5),url:'tomalo_suave_files/stroke_10.png'},{rect:new IWRect(621,-2,4,5),url:'tomalo_suave_files/stroke_11.png'},{rect:new IWRect(621,3,6,340),url:'tomalo_suave_files/stroke_12.png'},{rect:new IWRect(621,343,6,4),url:'tomalo_suave_files/stroke_13.png'},{rect:new IWRect(3,343,618,6),url:'tomalo_suave_files/stroke_14.png'},{rect:new IWRect(-3,343,6,6),url:'tomalo_suave_files/stroke_15.png'}],new IWSize(624,346))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('tomalo_suave_files/tomalo_suaveMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
